### PR TITLE
Fix/email

### LINKED ISSUE #222: [PE-D][Tester C] The email format does not match the one specified in the User guide.
The email format does not match the one specified in the User guide. The user guide mentions `the last portion of the domain must be at least two characters, for example: .com, .org, .cc` but the add and edit command doesn't check for it.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: arnav-goel10/ped#8

### PR DESCRIPTION
**Pull request by accountexeregister**
closes #222

### CODE REVIEW

File: src/main/java/tahub/contacts/model/person/Email.java [hunk 1]
```diff
@@ -9,27 +9,32 @@
...
+    // Regex for each domain part (labels)
+    private static final String DOMAIN_PART_REGEX = "[" + ALLOWED_DOMAIN_CHARS + "]+";
+
+    // Regex for the domain (including subdomains and TLD)
+    private static final String DOMAIN_REGEX = "("
+            + DOMAIN_PART_REGEX + "\\.)+" // One or more domain labels followed by '.'
+            + "[a-zA-Z]{2,}$"; // TLD with at least two letters
+
+    // Complete validation regex
+    public static final String VALIDATION_REGEX = PREFIX_REGEX + "@" + DOMAIN_REGEX;
```
Comment (Zeepheru) [inline src/main/java/tahub/contacts/model/person/Email.java:37]: Wow! Such cool REGEX!!!

**Review by Zeepheru — APPROVED** [review]
Yes yes yes
